core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import index

from django.conf.urls import handler404
from .views import custom_page_not_found

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('gestion/', include('main_apps.gestion.urls')),
    path('client/', include('main_apps.client.urls')),
    path('facture/', include('main_apps.facture.urls')),
    path('demande/', include('main_apps.demande_transport.urls')),
    path('camionneur/', include('main_apps.comionneur.urls')),
    path('settings/', include('main_apps.settings.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='account_login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='account_logout'),
    path('account/', include('allauth.urls')),
    path('api/', include('api.forms_api.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('<path:unknown_path>', custom_page_not_found),
]



    

main_apps/comionneur/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


app_name = 'comionneur'


urlpatterns = [
    path('',views.camionneur, name='camionneur'),
    path('list_camionneur/',views.list_camionneur, name='list_camionneur'),
    path('detail_camionneur/<int:pk>/', views.detail_camionneur, name='detail_camionneur'),
    path('delete_camionneur/<int:pk>/',views.delete_camionneur, name='delete_camionneur'),
    path('update_camionneur/<int:pk>/',views.update_camionneur, name='update_camionneur'),
    path('search/', views.search_view, name='search'),
]

main_apps/gestion/urls.py
from django.urls import path,include
from . import views



app_name = 'gestion'

urlpatterns = [
    
    path('', views.gestion, name='gestion'),
    
]

templates/camionneur/ajouter_camionneur.html
{% extends "_base.html" %}
{% load tailwind_filters %}
{% block content %}
<!-- Hire Us -->
<div class="px-2 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <div class="max-w-xl mx-auto">
    <div class="text-center">
      <h1 class="text-3xl font-bold text-gray-800 sm:text-4xl dark:text-white">
        Ready to hire us?
      </h1>
      <p class="mt-1 text-gray-600 dark:text-neutral-400">
        Tell us your story and we’ll be in touch.
      </p>
    </div>

    </secsion class="mt-12">
      <!-- Form -->
      <div class='p-12'>
        <form class="form-control" action="{% url "forms_api:ajouter_camionneur" %}" method="post">
          <div class="flex flex-wrap gap-10 -mx-3 mb-6 space-x-4 mt-8 rounded-full">
              {% csrf_token %}
              {{ form|crispy }}
          </div>

          <div class='flex justify-center gap-6'>
              <input class='btn cfeqx cf1ce ceqwg mt-5 p-4' type="submit" value="Submit">
              <a class="btn dark:bg-slate-800 p-4 border-slate-200 mt-5 dark:border-slate-700 c46uo cm7vt c6tg6" href="{% url 'gestion:gestion' %}">Cancel</a>
          </div>                
        </form>
      </div>
    </secsion>
    <!-- End Form -->
    </div>
  </div>
</div>
<!-- End Hire Us -->
{% endblock content %}

templates/camionneur/delete_camionneur.html
                                    <div class="flex items-center justify-center" x-data="{ modalOpen: false }">
                                        <button class="btn dark:bg-slate-800 border-slate-600 dark:border-slate-700 c46uo cm7vt c6tg6" href="{% url "comionneur:delete_camionneur" pk=camionneurs.id %} @click.prevent="modalOpen = true" aria-controls="danger-modal">
                                            <svg class="mr-2 c6tg6 c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                <path d="M5 7h2v6H5V7zm4 0h2v6H9V7zm3-6v2h4v2h-1v10c0 .6-.4 1-1 1H2c-.6 0-1-.4-1-1V5H0V3h4V1c0-.6.4-1 1-1h6c.6 0 1 .4 1 1zM6 2v1h4V2H6zm7 3H3v9h10V5z"></path>
                                            </svg>
                                            <span class="c9o7o">Delete</span>
                                        </button>

templates/camionneur/search_results.html
{% extends "_base.html" %}

{% block content %}
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16">
        {% if query %}
            <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">{{ query }}</h1>
            {% if results %}
                <ul class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">
                    {% for camionneur in results %}
                    <a href="{% url "comionneur:detail_camionneur" pk=camionneur.id %}">
                        <li class="mb-8">{{ camionneur.get_full_name }} - {{ camionneur.entreprise_employeur }}</li>
                    </a>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">Aucun résultat trouvé.</p>
            {% endif %}
            <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">Résultats pour "{{ query }}":</p>
            <ul class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">
                {% if results %}
                    {% for camionneur in results %}
                        <a href="{% url "comionneur:detail_camionneur" pk=camionneur.id %}">
                            <li class="mb-8">
                                {{ camionneur.get_full_name }} - {{ camionneur.entreprise_employeur }}
                            </li>
                        </a>
                    {% endfor %}
                {% else %}
                    <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">Aucun résultat trouvé.</p>
                {% endif %}
            </ul>
        {% else %}
            <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">Veuillez entrer un terme de recherche.</p>
        {% endif %}
    </div>
    <div class="flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0">
        <a 
            href="{% url "comionneur:list_camionneur" %}" class="py-3 px-5 sm:ms-4 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
            Previous
        </a>  
    </div>
</section>

{% endblock %}

templates/camionneur/update_camionneur.html
{% extends "_base.html" %}
{% load tailwind_filters %}
{% block content %}
<!-- Hire Us -->
<div class="px-2 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <div class="max-w-xl mx-auto">
    <div class="text-center">
      <h1 class="text-3xl font-bold text-gray-800 sm:text-4xl dark:text-white">
       vous allez mettre a jour un camionneur ?
      </h1>
    </div>

    </secsion class="mt-12">
      <!-- Form -->
      <div class='p-12'>
        <form class="form-group-sm" action="{% url 'comionneur:update_camionneur' pk=camionneur.id %}" method="post">
          <div class="flex flex-wrap gap-6 -mx-3 mb-6 space-x-4 mt-8 rounded-full">
              {% csrf_token %}
              {{ form|crispy }}
          </div>

          <div class='flex justify-center gap-6'>
              <input class='btn cfeqx cf1ce ceqwg mt-5 p-4' type="submit" value="Submit">
              <a class="btn dark:bg-slate-800 p-4 border-slate-200 mt-5 dark:border-slate-700 c46uo cm7vt c6tg6" href="{% url 'comionneur:list_camionneur' %}">Cancel</a>
          </div>

                      
        </form>
      </div>
    </secsion>
    <!-- End Form -->
    </div>
  </div>
</div>
<!-- End Hire Us -->
{% endblock content %}