core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import index

from django.conf.urls import handler404
from .views import custom_page_not_found

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('gestion/', include('main_apps.gestion.urls')),
    path('client/', include('main_apps.client.urls')),
    path('facture/', include('main_apps.facture.urls')),
    path('demande/', include('main_apps.demande_transport.urls')),
    path('camionneur/', include('main_apps.comionneur.urls')),
    path('settings/', include('main_apps.settings.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='account_login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='account_logout'),
    path('account/', include('allauth.urls')),
    path('api/', include('api.forms_api.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('<path:unknown_path>', custom_page_not_found),
]



    

main_apps/facture/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = 'facture'
urlpatterns = [
    path('',views.facture, name='facture'),
    path('list_facture/',views.list_facture, name='list_facture'),
    path('ajouter_facture/',views.ajouter_facture, name='ajouter_facture'),
    path('update_facture/',views.update_facture, name='update_facture'),
    path('delete_facture/',views.delete_facture, name='delete_facture'),
]

main_apps/settings/urls.py
from django.urls import path
from . import views

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = 'settings'

urlpatterns = [
    path('',views.settings, name='settings'),
    
]

main_apps/settings/views.py
from django.shortcuts import render
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from django.shortcuts import redirect
from django.contrib.auth.models import User
from main_apps.client.models import Client
# @receiver(user_logged_in)
# def user_logged_in_callback(sender, request, user, **kwargs):
#     if user.groups.filter(name='client').exists():
#         return redirect('client:client')
#     elif user.groups.filter(name='admin').exists():
#         return redirect('gestion:gestion')
#     elif user.groups.filter(name='Camionneurs').exists():
#         return redirect('camionnaire:camionnaire')
#     else:
#         # Redirection par défaut pour les utilisateurs sans groupe spécifié
#         return redirect('client:client')  # Vous devez définir cette vue

# Create your views here.
# @group_required('admin')
# @login_required(login_url='/account_login/')
def settings(request):
    users = Client.objects.all()
    return render(request, 'settings/settings.html', {'users':users})

templates/settings/settings.html
{% extends "_base.html" %}
{% load static %}
    {% block content %}
    
            <main class="ckut6">
                <div class="cewy4 clpyc cj3hv cofxq c3ff8 c9r0z c0ycj">

                    <!-- Page header -->
                    <div class="ce97l">

                        <!-- Title -->
                        <h1 class="text-slate-800 dark:text-slate-100 font-bold cy709 cjefr">Parametre du compte ✨</h1>

                    </div>

                    <div class="bg-white dark:bg-slate-800 rounded-sm cetne ce97l">
                        <div class="flex cygwm cfrx6 chmlm">

                            <!-- Sidebar -->
                            <div class="flex border-slate-200 dark:border-slate-700 cmgrv c7bxu cpcdz cf18b cz385 cqjax cmaja c108j ccg4t cz4zt cjm6w c3ntd">
                                <!-- Group 1 -->
                                <div>
                                    <div class="ciz4v czgoy cqosy cw3n3 c0qeg cvavu">Business settings</div>
                                    <ul class="flex cmaja c108j crc9s czt1n">
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c0ewf c626f ckcyd csq8i cfnh0" href="{% url 'settings:settings' %}">
                                                <svg class="text-indigo-400 mr-2 c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M12.311 9.527c-1.161-.393-1.85-.825-2.143-1.175A3.991 3.991 0 0012 5V4c0-2.206-1.794-4-4-4S4 1.794 4 4v1c0 1.406.732 2.639 1.832 3.352-.292.35-.981.782-2.142 1.175A3.942 3.942 0 001 13.26V16h14v-2.74c0-1.69-1.081-3.19-2.689-3.733zM6 4c0-1.103.897-2 2-2s2 .897 2 2v1c0 1.103-.897 2-2 2s-2-.897-2-2V4zm7 10H3v-.74c0-.831.534-1.569 1.33-1.838 1.845-.624 3-1.436 3.452-2.422h.436c.452.986 1.607 1.798 3.453 2.422A1.943 1.943 0 0113 13.26V14z"></path>
                                                </svg>
                                                <span class="text-sm text-indigo-500 cnzyq cw92y">My Account</span>
                                            </a>
                                        </li>
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c626f csq8i cfnh0" href="notifications.html">
                                                <svg class="mr-2 ciz4v czgoy c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M14.3.3c.4-.4 1-.4 1.4 0 .4.4.4 1 0 1.4l-8 8c-.2.2-.4.3-.7.3-.3 0-.5-.1-.7-.3-.4-.4-.4-1 0-1.4l8-8zM15 7c.6 0 1 .4 1 1 0 4.4-3.6 8-8 8s-8-3.6-8-8 3.6-8 8-8c.6 0 1 .4 1 1s-.4 1-1 1C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6c0-.6.4-1 1-1z"></path>
                                                </svg>
                                                <span class="text-sm cn6r0 cwxny ch1ih c6w4h cw92y">My Notifications</span>
                                            </a>
                                        </li>
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c626f csq8i cfnh0" href="connected-apps.html">
                                                <svg class="mr-2 ciz4v czgoy c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M3.414 2L9 7.586V16H7V8.414l-5-5V6H0V1a1 1 0 011-1h5v2H3.414zM15 0a1 1 0 011 1v5h-2V3.414l-3.172 3.172-1.414-1.414L12.586 2H10V0h5z"></path>
                                                </svg>
                                                <span class="text-sm cn6r0 cwxny ch1ih c6w4h cw92y">Connected Apps</span>
                                            </a>
                                        </li>
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c626f csq8i cfnh0" href="plans.html">
                                                <svg class="mr-2 ciz4v czgoy c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M5 9h11v2H5V9zM0 9h3v2H0V9zm5 4h6v2H5v-2zm-5 0h3v2H0v-2zm5-8h7v2H5V5zM0 5h3v2H0V5zm5-4h11v2H5V1zM0 1h3v2H0V1z"></path>
                                                </svg>
                                                <span class="text-sm cn6r0 cwxny ch1ih c6w4h cw92y">Plans</span>
                                            </a>
                                        </li>
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c626f csq8i cfnh0" href="{% url "facture:ajouter_facture" %}">
                                                <svg class="mr-2 ciz4v czgoy c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M15 4c.6 0 1 .4 1 1v10c0 .6-.4 1-1 1H3c-1.7 0-3-1.3-3-3V3c0-1.7 1.3-3 3-3h7c.6 0 1 .4 1 1v3h4zM2 3v1h7V2H3c-.6 0-1 .4-1 1zm12 11V6H2v7c0 .6.4 1 1 1h11zm-3-5h2v2h-2V9z"></path>
                                                </svg>
                                                <span class="text-sm cn6r0 cwxny ch1ih c6w4h cw92y">Ajouter &amp; une facture</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- Group 2 -->
                                <div>
                                    <div class="ciz4v czgoy cqosy cw3n3 c0qeg cvavu">Experience</div>
                                    <ul class="flex cmaja c108j crc9s czt1n">
                                        <li class="cid50 crc9s c6orf">
                                            <a class="flex items-center rounded c626f csq8i cfnh0" href="feedback.html">
                                                <svg class="mr-2 ciz4v czgoy c3wll c7n6y cgmrc cm474" viewBox="0 0 16 16">
                                                    <path d="M7.001 3h2v4h-2V3zm1 7a1 1 0 110-2 1 1 0 010 2zM15 16a1 1 0 01-.6-.2L10.667 13H1a1 1 0 01-1-1V1a1 1 0 011-1h14a1 1 0 011 1v14a1 1 0 01-1 1zM2 11h9a1 1 0 01.6.2L14 13V2H2v9z"></path>
                                                </svg>
                                                <span class="text-sm cn6r0 cwxny ch1ih c6w4h cw92y">Give Feedback</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <!-- Panel -->
                            <div class="ckut6">

                                <!-- Panel body -->
                                <div class="c3goj caod7">
                                    <h2 class="text-slate-800 dark:text-slate-100 font-bold cjefr cg5st">My Account</h2>

                                    <!-- Picture -->
                                    <section>
                                        <div class="flex items-center">
                                            <div class="mr-4">
                                                <img class="rounded-full chkq1 c4a13" src="{{ request.user.photo }}" width="80" height="80" alt="User upload">
                                            </div>
                                            <button class="cfeqx cf1ce ceqwg cjusy">Change</button>
                                        </div>
                                    </section>

                                    <!-- Business Profile -->
                                    <section>
                                        <h3 class="text-slate-800 dark:text-slate-100 font-bold ctbo0 cvvcr ci4cg">Business Profile</h3>
                                        <div class="text-sm">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit.</div>
                                        <div class="cxbdy c95r9 cuga1 cxebx clk9r cggtb">
                                            <div class="czb6y">
                                                <label class="block text-sm cw92y ci4cg" for="name">Business Name</label>
                                                <input id="name" class="c03gb c3ff8" type="text" value="Acme Inc.">
                                            </div>
                                            <div class="czb6y">
                                                <label class="block text-sm cw92y ci4cg" for="business-id">Business ID</label>
                                                <input id="business-id" class="c03gb c3ff8" type="text" value="Kz4tSEqtUmA">
                                            </div>
                                            <div class="czb6y">
                                                <label class="block text-sm cw92y ci4cg" for="location">Location</label>
                                                <input id="location" class="c03gb c3ff8" type="text" value="London, UK">
                                            </div>
                                        </div>
                                    </section>

                                    <!-- Email -->
                                    <section>
                                        <h3 class="text-slate-800 dark:text-slate-100 font-bold ctbo0 cvvcr ci4cg">Email</h3>
                                        <div class="text-sm">Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia.</div>
                                        <div class="flex flex-wrap cggtb">
                                            <div class="mr-2">
                                                <label class="cbl3h" for="email">Business email</label>
                                                <input id="email" class="c03gb" type="email" value="admin@acmeinc.com">
                                            </div>
                                            <button class="btn border-slate-200 dark:border-slate-700 text-indigo-500 c46uo cm7vt cl0q9">Change</button>
                                        </div>
                                    </section>

                                    <!-- Password -->
                                    <section>
                                        <h3 class="text-slate-800 dark:text-slate-100 font-bold ctbo0 cvvcr ci4cg">Password</h3>
                                        <div class="text-sm">You can set a permanent password if you don't want to use temporary login codes.</div>
                                        <div class="cggtb">
                                            <button class="btn border-slate-200 dark:border-slate-700 text-indigo-500 c46uo cm7vt cl0q9">Set New Password</button>
                                        </div>
                                    </section>

                                    <!-- Smart Sync -->
                                    <section>
                                        <h3 class="text-slate-800 dark:text-slate-100 font-bold ctbo0 cvvcr ci4cg">Smart Sync update for Mac</h3>
                                        <div class="text-sm">With this update, online-only files will no longer appear to take up hard drive space.</div>
                                        <div class="flex items-center cggtb" x-data="{ checked: true }">
                                            <div class="c987k">
                                                <input type="checkbox" id="toggle" class="cbl3h" x-model="checked">
                                                <label class="ce4zx c717g" for="toggle">
                                                    <span class="bg-white cl0q9" aria-hidden="true"></span>
                                                    <span class="cbl3h">Enable smart sync</span>
                                                </label>
                                            </div>
                                            <div class="text-sm ciz4v czgoy clmtf c9o7o" x-text="checked ? 'On' : 'Off'"></div>
                                        </div>
                                    </section>
                                </div>

                                <!-- Panel footer -->
                                <footer>
                                    <div class="flex border-slate-200 dark:border-slate-700 chmlm c87xd cdsqp c7s20">
                                        <div class="flex c93ao">
                                            <button class="btn dark:bg-slate-800 border-slate-200 dark:border-slate-700 c46uo cm7vt ch1ih c6w4h">Cancel</button>
                                            <button class="btn ml-3 cfeqx cf1ce ceqwg">Save Changes</button>
                                        </div>
                                    </div>
                                </footer>

                            </div>

                        </div>
                    </div>

                </div>
            </main>
    
    {% endblock content %}